//WIFLY CONFIG
#define SSID "SSID"
#define PASSPHRASE "PASSPHRASE"
#define TO_WIFLY_PIN 8 //TX
#define FROM_WIFLY_PIN 9 //RX

//TWITTER CONFIG
#define TWITTER_TOKEN "TWITTERTOKEN"
#define TWITTER_DELAY 60000
#define LIB_DOMAIN "arduino-tweet.appspot.com"

//INITIAL PLANT CONFIG
#define DRY 300
#define WET 100
#define DELTA_HUMID 20
